# Generated by Django 4.2.3 on 2024-09-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('chunk_number', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt_Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('prompt_type', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('persona', models.CharField(max_length=256)),
                ('persona_base_prompt', models.TextField()),
                ('output_format_type', models.TextField()),
                ('output_format_prompt', models.TextField()),
                ('prompt_text', models.TextField()),
                ('status', models.CharField(max_length=256)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_modified_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensitive_key', models.CharField(max_length=256)),
                ('sensitive_value', models.TextField()),
                ('additional_info', models.TextField(default='')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
